# Generated by Django 3.0.5 on 2020-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_selectedrepos'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthcode',
            name='access_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
