# Generated by Django 3.0.5 on 2020-04-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200418_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedrepos',
            name='open_issues',
        ),
    ]
